### ISSUE TITLE
Streams as message-framing

### ISSUE THREAD

**Issue by janaiyengar** [quicwg/ops-drafts#54] opened 2018-11-06 07:57 UTC
It's useful to talk about the use of streams as messages, since they're designed to be lightweight. This is a feature of QUIC, and it's worth articulating.

**Comment by janaiyengar** [comment] 2018-11-07 02:29
@dtikhonov: I don't want to litigate how QPACK ought to have been done here, but streams are defined to be usable in this manner. See [transport draft](https://quicwg.org/base-drafts/draft-ietf-quic-transport.html#rfc.section.2): "Streams in QUIC provide a lightweight, ordered byte-stream abstraction to an application. An alternative view of QUIC streams is as an elastic “message” abstraction."

**Comment by dtikhonov** [comment] 2018-11-07 04:07
My point is about the "lightweightedness" of QUIC streams, not about QPACK.

**Comment by janaiyengar** [comment] 2018-11-07 12:17
Since that's not an objectively-defined term, I think every use-case will
have to decide whether a QUIC stream is lightweight enough. That said, it's
still reasonable as a message abstraction, but maybe not _all_ use cases.

**Comment by britram** [comment] 2019-04-18 07:13
note that this is a partial dupe of #15 (which implicitly uses streams for message framing in order to make them variably-reliable). 

IMO, at least some language on this (if we want to do this, which I personally do) belongs in -transport, because while it is not _technically_ necessary to call out there for interoperability purposes, the fact that streams-as-messages is obvious enough in the shadows of the design to have occurred to multiple people mapping multiple different application protocols and APIs to QUIC means at least a pointer to the idea should be there (so as not to surprise people to whom it has not yet occurred).

**Comment by mirjak** [comment] 2019-04-18 08:11
Hm, I think this was discussed as some QUIC meeting a couple of IETFs ago and we agreed to have it (only) in manageability.

**Comment by MikeBishop** [comment] 2019-04-18 18:43
IIRC, the thought was that we'd rather have people use DATAGRAM for this purpose, once it's available.  Personally, I disagree with that stance, because streams-as-messages means you can have a message-based protocol that's not limited to the path MTU, which I find quite compelling.

**Comment by janaiyengar** [comment] 2019-04-18 22:45
I agree with @MikeBishop on the value, but I had thought that this really belonged in the applicability document. It is about how QUIC's abstractions may be used, which seems like an applicability point.

**Comment by mirjak** [comment] 2019-07-02 14:39
This is what is already in the doc: 
"If there is a logical grouping of those data chunks or messages, stream can be reused, or a new stream can be opened for each chunk/message."

I think that is sufficient. Can we close the issue?

**Comment by britram** [comment] 2019-07-02 14:40
+1 to closing this.

**Closed** 2019-07-04 13:46 UTC
Labels: -applicability
